### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by futures-dev** [Yorko/hse_DM_project_group3#18]
Add Hunter.EAT_CONST and Victim.VictimBreedTime to Settings Window plz
What is the last icon in Settings window for? Slider's value change does not affect that in Settings =/

**Comment by potykion** [comment]
Комментики по-русски буду. 

VictimBreedTime есть в Settings.
EAT_CONST надо переименовать тогда, я считал, что хищник ест/плодится рандомно.

Последняя иконка в SettingWindow - iteration delay или скорость.

Последнее не понял. 
Когда двигаешь слайдер, он дефолтное значение скорости умножает на значение слайдера, переведенное в проценты, и сохраняет в Settings как текущее значение скорости.

И новая проблема: когда жмешь ресет, то все вылетает.
